export const adBannerData = [
  {
    id: 1,
    title: 'On The Top',
    subtitle: '16팀, 데스크 테리어 추천 서비스 바로가기',
    backgroundColor: 'bg-gradient-to-r from-blue-500 to-blue-600',
    textColor: 'text-white',
    image: '🖥️',
    link: 'https://onthe-top.com/',
  },
  {
    id: 2,
    title: '탐나라',
    subtitle: '18팀, 당신의 이슈를 타임라인으로',
    backgroundColor: 'bg-gradient-to-r from-purple-500 to-purple-600',
    textColor: 'text-white',
    image: '🍊',
    link: 'https://tam-nara.com/main',
  },
  {
    id: 3,
    title: '춘이네 비서실',
    subtitle: '20팀, 카테부의 소식을 확인하세요!',
    backgroundColor: 'bg-gradient-to-r from-green-500 to-green-600',
    textColor: 'text-white',
    image: '📚',
    link: 'https://www.kakaotech.com/home',
  },
  {
    id: 4,
    title: 'Koco',
    subtitle: '21팀, 알고리즘 학습 서비스 바로가기',
    backgroundColor: 'bg-gradient-to-r from-orange-500 to-orange-600',
    textColor: 'text-white',
    image: '📊',
    link: 'https://ktbkoco.com/',
  },
  {
    id: 5,
    title: 'KakaoBase',
    subtitle: '22팀, 카테부 수강생 전용 커뮤니티',
    backgroundColor: 'bg-gradient-to-r from-teal-500 to-teal-600',
    textColor: 'text-white',
    image: '👥',
    link: 'https://www.kakaobase.com/',
  },
];
